### ISSUE TITLE
Log Info

### ISSUE THREAD

**Issue by sujithq** [Haplo-tech/Promote#17]
Is it possible to log more information like the url and payload? For some reason it stopped working. I Get this error:

Unsuccessful request, status code:404

![image](https://user-images.githubusercontent.com/1705501/55487426-5a996f00-562e-11e9-92c7-11449ebbd8df.png)
![image](https://user-images.githubusercontent.com/1705501/55487453-671dc780-562e-11e9-920f-8a39490f2c9f.png)

**Comment by gavanlamb** [comment]
Hi Sujith, 
Thanks for adding the issue. 
I'll add a debug toggle and logout the relevant information for all request and variables.

**Comment by gavanlamb** [comment]
Add debug logs
